fragment project on Project {
  id
  name
  website
  logoURL
  faviconURL
}

query project($includeDetails: Boolean! = false) {
  project {
    ...project
    
    ssoConfig @include(if: $includeDetails) {
      id
      ssoKey
    }
  }
}

mutation saveProject($input: SaveProjectInput!) {
  saveProject(input: $input) {
    ...project
  }
}

fragment invite on Invite {
  id
  email
  createdAt
  token
}

query lookupInvite($token: String!) {
  lookupInvite(token: $token) {
    ...invite
  }
}

query projectMembersAndInvites {
  members {
    ...user
  }

  invites {
    ...invite
  }
}

mutation removeUser($input: RemoveUserInput!) {
  removeUser(input: $input)
}

mutation addInvite($input: AddInviteInput!) {
  addInvite(input: $input) {
    id
  }
}

mutation removeInvite($input: RemoveInviteInput!) {
  removeInvite(input: $input)
}
