fragment boardSummary on Board {
  id
  name
  slug
  color
  isListed
}

fragment board on Board {
  ...boardSummary
}

query board($boardId: UUID, $boardSlug: String) {
  board(id: $boardId, slug: $boardSlug) {
    ...board
  }
}

query boards {
  boards {
    ...board
  }
}
